# Generated by Django 5.2.3 on 2025-06-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_unit_alter_entity_options_category_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='unit',
        ),
        migrations.AddField(
            model_name='computer',
            name='room',
            field=models.CharField(choices=[('EB204', 'EB204'), ('EB205', 'EB205'), ('EB206', 'EB206'), ('EB207', 'EB207'), ('EB208', 'EB208'), ('EB209', 'EB209'), ('EB210', 'EB210')], default='EB204', max_length=10),
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
