# Generated by Django 5.2.3 on 2025-06-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_category_unit_computer_room_delete_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='keyboard',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='computer',
            name='monitor_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='computer',
            name='monitor_serial_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='computer',
            name='motherboard_system_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='computer',
            name='mouse',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='computer',
            name='pc_unit_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='processor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='computer',
            name='ram',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='computer',
            name='ram_slot',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='computer',
            name='remarks',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='computer',
            name='storage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='computer',
            name='video_card_0',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='computer',
            name='video_card_1',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
