# Generated by Django 5.2.3 on 2025-06-28 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_computer_motherboard_system_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='hostname',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='item',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='os',
        ),
        migrations.DeleteModel(
            name='MaintenanceRecord',
        ),
    ]
