# Generated by Django 5.2.3 on 2025-06-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_computer_hostname_remove_computer_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='custody',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='office_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
