# Generated by Django 5.2.3 on 2025-06-30 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_computer_custody_computer_office_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer',
            old_name='office_name',
            new_name='entity_name',
        ),
    ]
