# Generated by Django 5.2.3 on 2025-06-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_item_mr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='mr',
        ),
        migrations.AddField(
            model_name='computer',
            name='mr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
