# Generated by Django 5.2.3 on 2025-07-02 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_item_mr_computer_mr'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccomplishedBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_started', models.DateTimeField()),
                ('type', models.CharField(choices=[('desktop', 'Desktop'), ('laptop', 'Laptop'), ('printer', 'Printer'), ('scanner', 'Scanner'), ('others', 'Others (specify)')], max_length=20)),
                ('description', models.TextField()),
                ('action_taken', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('datetime_completed', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.CharField(max_length=100)),
                ('conformed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('accomplished_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.accomplishedby')),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.entity')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.office')),
            ],
        ),
    ]
